/* clothing-catalog.js — Bites & Baits
 * Peças avulsas derivadas das descrições dos dez conjuntos iniciais.
 * Preços e decomposição visual são valores de protótipo, sujeitos a balanceamento.
 */
const CLOTHING_CATALOG = Object.freeze([
  { id:'top_light_casual', slot:'top', modes:['arrival'], price:10, color:'#d9e7e8',
    name:{pt:'Camiseta clara',en:'Light T-shirt',hu:'Világos póló'},
    description:{pt:'Peça superior do conjunto Casual claro.',en:'Top from the Light casual set.',hu:'A Világos hétköznapi összeállítás felsőrésze.'} },
  { id:'bottom_simple', slot:'bottom', modes:['arrival','fishing'], price:10, color:'#596570',
    name:{pt:'Calça simples',en:'Simple trousers',hu:'Egyszerű nadrág'},
    description:{pt:'Calça básica dos conjuntos iniciais.',en:'Basic trousers from the starter sets.',hu:'Alapnadrág a kezdő összeállításokból.'} },
  { id:'top_dark_casual', slot:'top', modes:['arrival'], price:10, color:'#355b70',
    name:{pt:'Camiseta escura',en:'Dark T-shirt',hu:'Sötét póló'},
    description:{pt:'Peça superior do conjunto Casual escuro.',en:'Top from the Dark casual set.',hu:'A Sötét hétköznapi összeállítás felsőrésze.'} },
  { id:'top_loose_comfort', slot:'top', modes:['arrival'], price:12, color:'#c9977c',
    name:{pt:'Blusa solta',en:'Loose top',hu:'Laza felső'},
    description:{pt:'Peça superior do conjunto Confortável.',en:'Top from the Comfortable set.',hu:'A Kényelmes összeállítás felsőrésze.'} },
  { id:'bottom_comfort', slot:'bottom', modes:['arrival'], price:12, color:'#857b70',
    name:{pt:'Calça confortável',en:'Comfortable trousers',hu:'Kényelmes nadrág'},
    description:{pt:'Calça confortável do conjunto Confortável.',en:'Comfortable trousers from the Comfortable set.',hu:'A Kényelmes összeállítás nadrágja.'} },
  { id:'top_urban', slot:'top', modes:['arrival'], price:14, color:'#8174a0',
    name:{pt:'Camisa urbana',en:'Urban shirt',hu:'Városi ing'},
    description:{pt:'Peça superior do conjunto Urbano.',en:'Top from the Urban set.',hu:'A Városi összeállítás felsőrésze.'} },
  { id:'jacket_light', slot:'outerwear', layer:'jacket', modes:['arrival'], price:20, color:'#59647d',
    name:{pt:'Jaqueta leve',en:'Light jacket',hu:'Könnyű dzseki'},
    description:{pt:'Alternativa de sobreposição para o conjunto Urbano.',en:'Optional layer for the Urban set.',hu:'Opcionális réteg a Városi összeállításhoz.'} },
  { id:'top_sturdy', slot:'top', modes:['arrival','fishing'], price:14, color:'#80664d',
    name:{pt:'Camisa resistente',en:'Sturdy shirt',hu:'Strapabíró felső'},
    description:{pt:'Peça superior simples e resistente.',en:'Simple, sturdy top.',hu:'Egyszerű, strapabíró felsőrész.'} },
  { id:'bottom_sturdy', slot:'bottom', modes:['arrival','fishing'], price:14, color:'#4c4d4c',
    name:{pt:'Calça resistente',en:'Sturdy trousers',hu:'Strapabíró nadrág'},
    description:{pt:'Calça resistente dos conjuntos de pesca.',en:'Sturdy trousers from the fishing sets.',hu:'Strapabíró nadrág a horgász összeállításokból.'} },
  { id:'top_fishing_light', slot:'top', modes:['fishing'], price:12, color:'#45778c',
    name:{pt:'Camisa leve de pesca',en:'Light fishing shirt',hu:'Könnyű horgászfelső'},
    description:{pt:'Peça superior do conjunto Pescador clássico.',en:'Top from the Classic angler set.',hu:'A Klasszikus horgász összeállítás felsőrésze.'} },
  { id:'vest_simple', slot:'outerwear', layer:'vest', modes:['fishing'], price:16, color:'#c3a46c',
    name:{pt:'Colete simples',en:'Simple vest',hu:'Egyszerű mellény'},
    description:{pt:'Colete leve do conjunto Pescador clássico.',en:'Simple vest from the Classic angler set.',hu:'Egyszerű mellény a Klasszikus horgász összeállításból.'} },
  { id:'top_river', slot:'top', modes:['fishing'], price:12, color:'#547b83',
    name:{pt:'Camisa do rio',en:'River shirt',hu:'Folyóparti felső'},
    description:{pt:'Tons azuis e terrosos, inspirados no conjunto Rio.',en:'Blue and earth tones inspired by the River set.',hu:'Kék és földszínek a Folyó összeállítás ihletésére.'} },
  { id:'vest_light', slot:'outerwear', layer:'vest', modes:['fishing'], price:16, color:'#8b806b',
    name:{pt:'Camada leve de proteção',en:'Light protective layer',hu:'Könnyű védőréteg'},
    description:{pt:'Sobreposição leve do conjunto Rio.',en:'Light outer layer from the River set.',hu:'Könnyű felső réteg a Folyó összeállításból.'} },
  { id:'top_lake', slot:'top', modes:['fishing'], price:12, color:'#67885d',
    name:{pt:'Camisa do lago',en:'Lake shirt',hu:'Tavi felső'},
    description:{pt:'Peça superior em tons verdes do conjunto Lago.',en:'Green-toned top from the Lake set.',hu:'Zöld felsőrész a Tó összeállításból.'} },
  { id:'sun_hat', slot:'headwear', modes:['fishing'], price:14, color:'#b38b4f',
    name:{pt:'Chapéu de sol',en:'Sun hat',hu:'Napkalap'},
    description:{pt:'Peça de proteção solar do conjunto Lago.',en:'Sun-protection piece from the Lake set.',hu:'Napvédő darab a Tó összeállításból.'} },
  { id:'rain_cape', slot:'outerwear', layer:'cape', modes:['fishing'], price:22, color:'#5d7a90',
    name:{pt:'Capa leve de chuva',en:'Light rain cape',hu:'Könnyű esőköpeny'},
    description:{pt:'Capa do conjunto Chuva.',en:'Cape from the Rain set.',hu:'Köpeny az Eső összeállításból.'} },
  { id:'top_waterproof', slot:'top', modes:['fishing'], price:18, color:'#416b7f',
    name:{pt:'Blusa impermeável',en:'Waterproof top',hu:'Vízálló felső'},
    description:{pt:'Peça impermeável do conjunto Chuva.',en:'Waterproof piece from the Rain set.',hu:'Vízálló darab az Eső összeállításból.'} },
  { id:'bottom_waterproof', slot:'bottom', modes:['fishing'], price:18, color:'#455c67',
    name:{pt:'Calça impermeável',en:'Waterproof trousers',hu:'Vízálló nadrág'},
    description:{pt:'Calça impermeável do conjunto Chuva.',en:'Waterproof trousers from the Rain set.',hu:'Vízálló nadrág az Eső összeállításból.'} },
  { id:'vest_reinforced', slot:'outerwear', layer:'vest', modes:['fishing'], price:22, color:'#66513f',
    name:{pt:'Colete reforçado',en:'Reinforced vest',hu:'Megerősített mellény'},
    description:{pt:'Colete do conjunto Trabalho pesado.',en:'Vest from the Heavy work set.',hu:'Mellény a Nehéz munka összeállításból.'} },
  { id:'fishing_gloves', slot:'gloves', modes:['fishing'], price:8, color:'#655e50',
    name:{pt:'Luvas de pesca',en:'Fishing gloves',hu:'Horgászkesztyű'},
    description:{pt:'Luvas visuais do conjunto Trabalho pesado.',en:'Gloves from the Heavy work set.',hu:'Kesztyű a Nehéz munka összeállításból.'} },
]);

const CLOTHING_STARTER_SETS = Object.freeze({
  arrival: Object.freeze({
    1: { top:'top_light_casual', bottom:'bottom_simple' },
    2: { top:'top_dark_casual', bottom:'bottom_simple' },
    3: { top:'top_loose_comfort', bottom:'bottom_comfort' },
    4: { top:'top_urban', bottom:'bottom_simple' },
    5: { top:'top_sturdy', bottom:'bottom_sturdy' },
  }),
  fishing: Object.freeze({
    1: { top:'top_fishing_light', bottom:'bottom_sturdy', outerwear:'vest_simple' },
    2: { top:'top_river', bottom:'bottom_sturdy', outerwear:'vest_light' },
    3: { top:'top_lake', bottom:'bottom_sturdy', headwear:'sun_hat' },
    4: { top:'top_waterproof', bottom:'bottom_waterproof', outerwear:'rain_cape' },
    5: { top:'top_sturdy', bottom:'bottom_sturdy', outerwear:'vest_reinforced', gloves:'fishing_gloves' },
  }),
});

function getClothingItem(id) {
  return CLOTHING_CATALOG.find(item => item.id === id) || null;
}
